<?php

/**
 * @file
 * Contains telephone_international_widget.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function telephone_international_widget_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the telephone_international_widget module.
    case 'help.page.telephone_international_widget':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('A JavaScript plugin for entering and validating international telephone numbers.') . '</p>';
      return $output;

    default:
  }
}
